/**
 * Session-scoped terminal mailbox protocol.
 *
 * This intentionally has no WebContainer or Node imports.  The browser and
 * the host use the same small envelope and path rules; the mailbox itself is
 * only a transport and never contains shell/editor state.
 */
import { isValidInstanceId } from '../engine/host-route.js';

export const TERMINAL_PROTOCOL_VERSION = 1 as const;
export const TERMINAL_MAILBOX_ROOT = '/.succinix-terminal';
export const TERMINAL_FRAME_LIMIT = 32 * 1024;
export const TERMINAL_FLUSH_MS = 16;
export const TERMINAL_MAX_BUFFER_BYTES = 1024 * 1024;
/** A disconnected browser must not keep an execution-world mailbox forever. */
export const TERMINAL_HEARTBEAT_MS = 10_000;
export const TERMINAL_SESSION_TTL_MS = 30_000;

export type TerminalFrameKind = 'input' | 'resize' | 'focus' | 'clear' | 'heartbeat' | 'dispose';

export interface TerminalIdentity {
  protocolVersion: typeof TERMINAL_PROTOCOL_VERSION;
  sessionId: string;
  instanceId: string;
  bootNonce: string;
}

export interface TerminalOpenFrame extends TerminalIdentity {
  type: 'open';
  cols: number;
  rows: number;
  lastAck?: number;
}

export interface TerminalInputFrame extends TerminalIdentity {
  type: TerminalFrameKind;
  seq: number;
  data?: string;
  cols?: number;
  rows?: number;
}

export interface TerminalOutputFrame extends TerminalIdentity {
  type: 'output';
  seq: number;
  data?: string;
  control?: 'focus' | 'clear' | 'resize' | 'backpressure';
  cols?: number;
  rows?: number;
  bufferedBytes?: number;
}

export interface TerminalAckFrame extends TerminalIdentity {
  type: 'ack';
  ack: number;
}

export interface TerminalErrorFrame extends TerminalIdentity {
  type: 'error';
  code: 'STALE_NONCE' | 'INVALID_FRAME' | 'BACKPRESSURE';
  message: string;
}

/** A terminal producer must retry the complete write after capacity is freed. */
export class TerminalBackpressureError extends Error {
  readonly code = 'TERMINAL_BACKPRESSURE';

  constructor(readonly attemptedBytes: number, readonly availableBytes: number) {
    super(`terminal backpressure: write of ${attemptedBytes} bytes exceeds ${availableBytes} available bytes`);
    this.name = 'TerminalBackpressureError';
  }
}

export function safeTerminalPart(value: string): string {
  // IDs are generated by the client, but treating the path component as
  // untrusted keeps mailbox writes fail-closed for third-party clients.  URL
  // escaping preserves valid instance IDs such as `users/alice` without
  // allowing a slash or `..` to escape the session mailbox.
  if (!validIdentityPart(value)) throw new Error('invalid terminal id');
  const encoded = encodeURIComponent(value);
  if (encoded === '.' || encoded === '..' || encoded.includes('/')) throw new Error('invalid terminal id');
  return encoded;
}

export function mailboxPath(identity: Pick<TerminalIdentity, 'instanceId' | 'sessionId'>, name: string): string {
  if (!isValidInstanceId(identity.instanceId)) throw new Error('invalid terminal id');
  const instance = safeTerminalPart(identity.instanceId);
  const session = safeTerminalPart(identity.sessionId);
  if (!/^[A-Za-z0-9._~-]+\.json$/.test(name)) throw new Error('invalid terminal mailbox filename');
  return `${TERMINAL_MAILBOX_ROOT}/${instance}/${session}/${name}`;
}

export function hostMailboxPath(identity: Pick<TerminalIdentity, 'instanceId' | 'sessionId'>, name: string): string {
  return mailboxPath(identity, name).slice(1);
}

export function frameFile(prefix: 'in' | 'out', seq: number): string {
  if (!Number.isSafeInteger(seq) || seq < 1) throw new Error('invalid terminal sequence');
  return `${prefix}-${String(seq).padStart(12, '0')}.json`;
}

export function parseFrameSequence(name: string, prefix: 'in' | 'out'): number | null {
  const m = new RegExp(`^${prefix}-(\\d{1,12})\\.json$`).exec(name);
  if (!m) return null;
  const n = Number(m[1]);
  return Number.isSafeInteger(n) && n > 0 ? n : null;
}

export function isTerminalIdentity(value: unknown): value is TerminalIdentity {
  if (!value || typeof value !== 'object') return false;
  const v = value as Partial<TerminalIdentity>;
  return v.protocolVersion === TERMINAL_PROTOCOL_VERSION &&
    typeof v.sessionId === 'string' && validIdentityPart(v.sessionId) &&
    isValidInstanceId(v.instanceId) &&
    typeof v.bootNonce === 'string' && validIdentityPart(v.bootNonce);
}

function validIdentityPart(value: string): boolean {
  return value.length > 0 && value.length <= 128 && !/[\u0000\u0001-\u001f\u007f]/.test(value);
}
