#!/usr/bin/env node
// WebUnix TASK20：零依赖 pre-commit 安装脚本。
// 写 .git/hooks/pre-commit 为可执行 wrapper，指向 scripts/pre-commit.sh。
// 幂等：已指向本项目脚本时跳过；--force 强制重写。
import { writeFileSync, chmodSync, readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const HOOK = join(ROOT, '.git', 'hooks', 'pre-commit');
const TARGET = join(ROOT, 'scripts', 'pre-commit.sh');

const force = process.argv.slice(2).includes('--force');

const wrapper = `#!/usr/bin/env bash
# Generated by \`npm run setup:hooks\` (WebUnix TASK20). Re-run to regenerate;
# the real logic lives in scripts/pre-commit.sh.
exec bash "${TARGET}"
`;

if (existsSync(HOOK)) {
  const existing = readFileSync(HOOK, 'utf8');
  // TASK21：保护第三方/既有 hook —— 文件已存在且内容不含本脚本时，绝不在非 --force 下
  // 静默覆盖（可能是用户自己的 hook 或其他工具安装的）。提示加 --force 并退出非零。
  if (!force && !existing.includes('scripts/pre-commit.sh')) {
    console.error(
      '[setup:hooks] .git/hooks/pre-commit already exists and is not managed by this project — ' +
        'refusing to overwrite it silently. Re-run with --force to replace it.'
    );
    process.exit(1);
  }
  if (!force && existing.includes('scripts/pre-commit.sh')) {
    console.log('[setup:hooks] .git/hooks/pre-commit already points to scripts/pre-commit.sh (--force to rewrite)');
    process.exit(0);
  }
}

writeFileSync(HOOK, wrapper);
chmodSync(HOOK, 0o755);
console.log(`[setup:hooks] wrote ${HOOK} -> ${TARGET}`);
